### ISSUE TITLE
Install from source fails on Windows 10

### ISSUE THREAD

**Issue by dalewsteele** [harrelfe/rmsb#3]
I attempted to install from source on Windows 10 using R 4.02 running in RStudio Preview v.1073 and rtools installed.

 Fails with compilation failed error:

```
...
C:/rtools40/mingw64/bin/g++ -shared -s -static-libgcc -o rmsb.dll tmp.def RcppExports.o stanExports_lrmconppo.o stanExports_lrmcppo.o -LC:/PROGRA~1/R/R-4.0.2/library/RcppParallel/lib/x64 -ltbb -ltbbmalloc -LC:/Program Files/R/R-4.0.2/library/RcppParallel/lib/x64 -Wl,-rpath,C:/Program Files/R/R-4.0.2/library/RcppParallel/lib/x64 -ltbb -ltbbmalloc -LC:/PROGRA~1/R/R-4.0.2/bin/x64 -lR
g++.exe: error: Files/R/R-4.0.2/library/RcppParallel/lib/x64: No such file or directory
no DLL was created
ERROR: compilation failed for package 'rmsb'
* removing 'C:/Program Files/R/R-4.0.2/library/rmsb'
Warning in install.packages :
  installation of package ‘rmsb’ had non-zero exit status

```

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.2 tools_4.0.2

**Comment by harrelfe** [comment]
This is not a rmsb problem but is a general problem with your system configuration when compiling C++ code in packages.  There is a binary package available for Windows; just use that.
