### ISSUE TITLE
Warning message: `survConcordance.fit` is deprecated

### ISSUE THREAD

**Issue by krassowski** [harrelfe/rmsb#5]
It seems that the code in:

https://github.com/harrelfe/rmsb/blob/741eece7f5579f58dbe29e8d718281132dd1e676/R/blrm.r#L680-L684

needs to be updated to avoid the repetitive warning:

```
Warning message:
“'survival::survConcordance.fit' is deprecated.
Use 'concordancefit' instead.
See help("Deprecated")”
```

**Comment by harrelfe** [comment]
This was fixed in the last CRAN release, replacing the call with the new concordance function in `survival`.
